/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBlogScopeProvider extends DelegatingScopeProvider {
}
