/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.blog.blog.BlogPackage;
import org.xtext.example.blog.blog.SectionContent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Section Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SectionContentImpl extends MinimalEObjectImpl.Container implements SectionContent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SectionContentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlogPackage.Literals.SECTION_CONTENT;
  }

} //SectionContentImpl
