/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.blog.blog.BlogPackage;
import org.xtext.example.blog.blog.Page;
import org.xtext.example.blog.blog.Site;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Site</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.blog.blog.impl.SiteImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.impl.SiteImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.impl.SiteImpl#isHasNavbar <em>Has Navbar</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.impl.SiteImpl#getIconUrl <em>Icon Url</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.impl.SiteImpl#getPages <em>Pages</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SiteImpl extends MinimalEObjectImpl.Container implements Site
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #isHasNavbar() <em>Has Navbar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHasNavbar()
   * @generated
   * @ordered
   */
  protected static final boolean HAS_NAVBAR_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isHasNavbar() <em>Has Navbar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHasNavbar()
   * @generated
   * @ordered
   */
  protected boolean hasNavbar = HAS_NAVBAR_EDEFAULT;

  /**
   * The default value of the '{@link #getIconUrl() <em>Icon Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIconUrl()
   * @generated
   * @ordered
   */
  protected static final String ICON_URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIconUrl() <em>Icon Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIconUrl()
   * @generated
   * @ordered
   */
  protected String iconUrl = ICON_URL_EDEFAULT;

  /**
   * The cached value of the '{@link #getPages() <em>Pages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPages()
   * @generated
   * @ordered
   */
  protected EList<Page> pages;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SiteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlogPackage.Literals.SITE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlogPackage.SITE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlogPackage.SITE__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isHasNavbar()
  {
    return hasNavbar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHasNavbar(boolean newHasNavbar)
  {
    boolean oldHasNavbar = hasNavbar;
    hasNavbar = newHasNavbar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlogPackage.SITE__HAS_NAVBAR, oldHasNavbar, hasNavbar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIconUrl()
  {
    return iconUrl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIconUrl(String newIconUrl)
  {
    String oldIconUrl = iconUrl;
    iconUrl = newIconUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlogPackage.SITE__ICON_URL, oldIconUrl, iconUrl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Page> getPages()
  {
    if (pages == null)
    {
      pages = new EObjectContainmentEList<Page>(Page.class, this, BlogPackage.SITE__PAGES);
    }
    return pages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BlogPackage.SITE__PAGES:
        return ((InternalEList<?>)getPages()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BlogPackage.SITE__NAME:
        return getName();
      case BlogPackage.SITE__DESCRIPTION:
        return getDescription();
      case BlogPackage.SITE__HAS_NAVBAR:
        return isHasNavbar();
      case BlogPackage.SITE__ICON_URL:
        return getIconUrl();
      case BlogPackage.SITE__PAGES:
        return getPages();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BlogPackage.SITE__NAME:
        setName((String)newValue);
        return;
      case BlogPackage.SITE__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case BlogPackage.SITE__HAS_NAVBAR:
        setHasNavbar((Boolean)newValue);
        return;
      case BlogPackage.SITE__ICON_URL:
        setIconUrl((String)newValue);
        return;
      case BlogPackage.SITE__PAGES:
        getPages().clear();
        getPages().addAll((Collection<? extends Page>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BlogPackage.SITE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case BlogPackage.SITE__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case BlogPackage.SITE__HAS_NAVBAR:
        setHasNavbar(HAS_NAVBAR_EDEFAULT);
        return;
      case BlogPackage.SITE__ICON_URL:
        setIconUrl(ICON_URL_EDEFAULT);
        return;
      case BlogPackage.SITE__PAGES:
        getPages().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BlogPackage.SITE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case BlogPackage.SITE__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case BlogPackage.SITE__HAS_NAVBAR:
        return hasNavbar != HAS_NAVBAR_EDEFAULT;
      case BlogPackage.SITE__ICON_URL:
        return ICON_URL_EDEFAULT == null ? iconUrl != null : !ICON_URL_EDEFAULT.equals(iconUrl);
      case BlogPackage.SITE__PAGES:
        return pages != null && !pages.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", description: ");
    result.append(description);
    result.append(", hasNavbar: ");
    result.append(hasNavbar);
    result.append(", iconUrl: ");
    result.append(iconUrl);
    result.append(')');
    return result.toString();
  }

} //SiteImpl
