/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.blog.blog.BlogFactory
 * @model kind="package"
 * @generated
 */
public interface BlogPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "blog";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/blog/Blog";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "blog";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BlogPackage eINSTANCE = org.xtext.example.blog.blog.impl.BlogPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.ModelImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Images</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__IMAGES = 0;

  /**
   * The feature id for the '<em><b>Categories</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CATEGORIES = 1;

  /**
   * The feature id for the '<em><b>Site</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SITE = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.ImageImpl <em>Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.ImageImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getImage()
   * @generated
   */
  int IMAGE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__URL = 1;

  /**
   * The number of structural features of the '<em>Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.CategoryImpl <em>Category</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.CategoryImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getCategory()
   * @generated
   */
  int CATEGORY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATEGORY__NAME = 0;

  /**
   * The number of structural features of the '<em>Category</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATEGORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.SiteImpl <em>Site</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.SiteImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getSite()
   * @generated
   */
  int SITE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Has Navbar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE__HAS_NAVBAR = 2;

  /**
   * The feature id for the '<em><b>Icon Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE__ICON_URL = 3;

  /**
   * The feature id for the '<em><b>Pages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE__PAGES = 4;

  /**
   * The number of structural features of the '<em>Site</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.PageImpl <em>Page</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.PageImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getPage()
   * @generated
   */
  int PAGE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Categories</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__CATEGORIES = 2;

  /**
   * The feature id for the '<em><b>Sections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__SECTIONS = 3;

  /**
   * The number of structural features of the '<em>Page</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.SectionImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getSection()
   * @generated
   */
  int SECTION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__CONTENT = 1;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.SectionContentImpl <em>Section Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.SectionContentImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getSectionContent()
   * @generated
   */
  int SECTION_CONTENT = 6;

  /**
   * The number of structural features of the '<em>Section Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_CONTENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.ParagraphContentImpl <em>Paragraph Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.ParagraphContentImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getParagraphContent()
   * @generated
   */
  int PARAGRAPH_CONTENT = 7;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAPH_CONTENT__CONTENT = SECTION_CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Paragraph Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAPH_CONTENT_FEATURE_COUNT = SECTION_CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.blog.blog.impl.ImageContentImpl <em>Image Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.blog.blog.impl.ImageContentImpl
   * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getImageContent()
   * @generated
   */
  int IMAGE_CONTENT = 8;

  /**
   * The feature id for the '<em><b>Image</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_CONTENT__IMAGE = SECTION_CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Image Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_CONTENT_FEATURE_COUNT = SECTION_CONTENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.blog.blog.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.blog.blog.Model#getImages <em>Images</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Images</em>'.
   * @see org.xtext.example.blog.blog.Model#getImages()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Images();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.blog.blog.Model#getCategories <em>Categories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Categories</em>'.
   * @see org.xtext.example.blog.blog.Model#getCategories()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Categories();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.blog.blog.Model#getSite <em>Site</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Site</em>'.
   * @see org.xtext.example.blog.blog.Model#getSite()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Site();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.Image <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image</em>'.
   * @see org.xtext.example.blog.blog.Image
   * @generated
   */
  EClass getImage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Image#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.blog.blog.Image#getName()
   * @see #getImage()
   * @generated
   */
  EAttribute getImage_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Image#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.blog.blog.Image#getUrl()
   * @see #getImage()
   * @generated
   */
  EAttribute getImage_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.Category <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Category</em>'.
   * @see org.xtext.example.blog.blog.Category
   * @generated
   */
  EClass getCategory();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Category#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.blog.blog.Category#getName()
   * @see #getCategory()
   * @generated
   */
  EAttribute getCategory_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.Site <em>Site</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Site</em>'.
   * @see org.xtext.example.blog.blog.Site
   * @generated
   */
  EClass getSite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Site#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.blog.blog.Site#getName()
   * @see #getSite()
   * @generated
   */
  EAttribute getSite_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Site#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.example.blog.blog.Site#getDescription()
   * @see #getSite()
   * @generated
   */
  EAttribute getSite_Description();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Site#isHasNavbar <em>Has Navbar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Navbar</em>'.
   * @see org.xtext.example.blog.blog.Site#isHasNavbar()
   * @see #getSite()
   * @generated
   */
  EAttribute getSite_HasNavbar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Site#getIconUrl <em>Icon Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Icon Url</em>'.
   * @see org.xtext.example.blog.blog.Site#getIconUrl()
   * @see #getSite()
   * @generated
   */
  EAttribute getSite_IconUrl();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.blog.blog.Site#getPages <em>Pages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pages</em>'.
   * @see org.xtext.example.blog.blog.Site#getPages()
   * @see #getSite()
   * @generated
   */
  EReference getSite_Pages();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.Page <em>Page</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page</em>'.
   * @see org.xtext.example.blog.blog.Page
   * @generated
   */
  EClass getPage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Page#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.blog.blog.Page#getName()
   * @see #getPage()
   * @generated
   */
  EAttribute getPage_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Page#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.example.blog.blog.Page#getDescription()
   * @see #getPage()
   * @generated
   */
  EAttribute getPage_Description();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.blog.blog.Page#getCategories <em>Categories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Categories</em>'.
   * @see org.xtext.example.blog.blog.Page#getCategories()
   * @see #getPage()
   * @generated
   */
  EReference getPage_Categories();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.blog.blog.Page#getSections <em>Sections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sections</em>'.
   * @see org.xtext.example.blog.blog.Page#getSections()
   * @see #getPage()
   * @generated
   */
  EReference getPage_Sections();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see org.xtext.example.blog.blog.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.Section#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.blog.blog.Section#getName()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.blog.blog.Section#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Content</em>'.
   * @see org.xtext.example.blog.blog.Section#getContent()
   * @see #getSection()
   * @generated
   */
  EReference getSection_Content();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.SectionContent <em>Section Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section Content</em>'.
   * @see org.xtext.example.blog.blog.SectionContent
   * @generated
   */
  EClass getSectionContent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.ParagraphContent <em>Paragraph Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paragraph Content</em>'.
   * @see org.xtext.example.blog.blog.ParagraphContent
   * @generated
   */
  EClass getParagraphContent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.blog.blog.ParagraphContent#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.xtext.example.blog.blog.ParagraphContent#getContent()
   * @see #getParagraphContent()
   * @generated
   */
  EAttribute getParagraphContent_Content();

  /**
   * Returns the meta object for class '{@link org.xtext.example.blog.blog.ImageContent <em>Image Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image Content</em>'.
   * @see org.xtext.example.blog.blog.ImageContent
   * @generated
   */
  EClass getImageContent();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.blog.blog.ImageContent#getImage <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Image</em>'.
   * @see org.xtext.example.blog.blog.ImageContent#getImage()
   * @see #getImageContent()
   * @generated
   */
  EReference getImageContent_Image();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BlogFactory getBlogFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.ModelImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Images</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__IMAGES = eINSTANCE.getModel_Images();

    /**
     * The meta object literal for the '<em><b>Categories</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CATEGORIES = eINSTANCE.getModel_Categories();

    /**
     * The meta object literal for the '<em><b>Site</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SITE = eINSTANCE.getModel_Site();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.ImageImpl <em>Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.ImageImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getImage()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getImage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__NAME = eINSTANCE.getImage_Name();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__URL = eINSTANCE.getImage_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.CategoryImpl <em>Category</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.CategoryImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getCategory()
     * @generated
     */
    EClass CATEGORY = eINSTANCE.getCategory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CATEGORY__NAME = eINSTANCE.getCategory_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.SiteImpl <em>Site</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.SiteImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getSite()
     * @generated
     */
    EClass SITE = eINSTANCE.getSite();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SITE__NAME = eINSTANCE.getSite_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SITE__DESCRIPTION = eINSTANCE.getSite_Description();

    /**
     * The meta object literal for the '<em><b>Has Navbar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SITE__HAS_NAVBAR = eINSTANCE.getSite_HasNavbar();

    /**
     * The meta object literal for the '<em><b>Icon Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SITE__ICON_URL = eINSTANCE.getSite_IconUrl();

    /**
     * The meta object literal for the '<em><b>Pages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SITE__PAGES = eINSTANCE.getSite_Pages();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.PageImpl <em>Page</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.PageImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getPage()
     * @generated
     */
    EClass PAGE = eINSTANCE.getPage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE__NAME = eINSTANCE.getPage_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE__DESCRIPTION = eINSTANCE.getPage_Description();

    /**
     * The meta object literal for the '<em><b>Categories</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE__CATEGORIES = eINSTANCE.getPage_Categories();

    /**
     * The meta object literal for the '<em><b>Sections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE__SECTIONS = eINSTANCE.getPage_Sections();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.SectionImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__NAME = eINSTANCE.getSection_Name();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__CONTENT = eINSTANCE.getSection_Content();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.SectionContentImpl <em>Section Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.SectionContentImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getSectionContent()
     * @generated
     */
    EClass SECTION_CONTENT = eINSTANCE.getSectionContent();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.ParagraphContentImpl <em>Paragraph Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.ParagraphContentImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getParagraphContent()
     * @generated
     */
    EClass PARAGRAPH_CONTENT = eINSTANCE.getParagraphContent();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAGRAPH_CONTENT__CONTENT = eINSTANCE.getParagraphContent_Content();

    /**
     * The meta object literal for the '{@link org.xtext.example.blog.blog.impl.ImageContentImpl <em>Image Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.blog.blog.impl.ImageContentImpl
     * @see org.xtext.example.blog.blog.impl.BlogPackageImpl#getImageContent()
     * @generated
     */
    EClass IMAGE_CONTENT = eINSTANCE.getImageContent();

    /**
     * The meta object literal for the '<em><b>Image</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE_CONTENT__IMAGE = eINSTANCE.getImageContent_Image();

  }

} //BlogPackage
