/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.blog.blog.ImageContent#getImage <em>Image</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.blog.blog.BlogPackage#getImageContent()
 * @model
 * @generated
 */
public interface ImageContent extends SectionContent
{
  /**
   * Returns the value of the '<em><b>Image</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image</em>' reference.
   * @see #setImage(Image)
   * @see org.xtext.example.blog.blog.BlogPackage#getImageContent_Image()
   * @model
   * @generated
   */
  Image getImage();

  /**
   * Sets the value of the '{@link org.xtext.example.blog.blog.ImageContent#getImage <em>Image</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image</em>' reference.
   * @see #getImage()
   * @generated
   */
  void setImage(Image value);

} // ImageContent
