/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paragraph Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.blog.blog.ParagraphContent#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.blog.blog.BlogPackage#getParagraphContent()
 * @model
 * @generated
 */
public interface ParagraphContent extends SectionContent
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see org.xtext.example.blog.blog.BlogPackage#getParagraphContent_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link org.xtext.example.blog.blog.ParagraphContent#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

} // ParagraphContent
