/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Section Content</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.blog.blog.BlogPackage#getSectionContent()
 * @model
 * @generated
 */
public interface SectionContent extends EObject
{
} // SectionContent
