/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.blog;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Site</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.blog.blog.Site#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.Site#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.Site#isHasNavbar <em>Has Navbar</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.Site#getIconUrl <em>Icon Url</em>}</li>
 *   <li>{@link org.xtext.example.blog.blog.Site#getPages <em>Pages</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.blog.blog.BlogPackage#getSite()
 * @model
 * @generated
 */
public interface Site extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.blog.blog.BlogPackage#getSite_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.blog.blog.Site#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.example.blog.blog.BlogPackage#getSite_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.blog.blog.Site#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Has Navbar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Navbar</em>' attribute.
   * @see #setHasNavbar(boolean)
   * @see org.xtext.example.blog.blog.BlogPackage#getSite_HasNavbar()
   * @model
   * @generated
   */
  boolean isHasNavbar();

  /**
   * Sets the value of the '{@link org.xtext.example.blog.blog.Site#isHasNavbar <em>Has Navbar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Navbar</em>' attribute.
   * @see #isHasNavbar()
   * @generated
   */
  void setHasNavbar(boolean value);

  /**
   * Returns the value of the '<em><b>Icon Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Icon Url</em>' attribute.
   * @see #setIconUrl(String)
   * @see org.xtext.example.blog.blog.BlogPackage#getSite_IconUrl()
   * @model
   * @generated
   */
  String getIconUrl();

  /**
   * Sets the value of the '{@link org.xtext.example.blog.blog.Site#getIconUrl <em>Icon Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Icon Url</em>' attribute.
   * @see #getIconUrl()
   * @generated
   */
  void setIconUrl(String value);

  /**
   * Returns the value of the '<em><b>Pages</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.blog.blog.Page}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pages</em>' containment reference list.
   * @see org.xtext.example.blog.blog.BlogPackage#getSite_Pages()
   * @model containment="true"
   * @generated
   */
  EList<Page> getPages();

} // Site
