/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BlogUiModule extends AbstractBlogUiModule {

	public BlogUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
