/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.blog.parser.antlr.internal.InternalBlogParser;
import org.xtext.example.blog.services.BlogGrammarAccess;

public class BlogParser extends AbstractAntlrParser {

	@Inject
	private BlogGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBlogParser createParser(XtextTokenStream stream) {
		return new InternalBlogParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BlogGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BlogGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
