/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BlogStandaloneSetup extends BlogStandaloneSetupGenerated {

	public static void doSetup() {
		new BlogStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
