/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlogRuntimeModule extends AbstractBlogRuntimeModule {
}
