/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.blog.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.blog.ui.internal.BlogActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BlogExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BlogActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BlogActivator activator = BlogActivator.getInstance();
		return activator != null ? activator.getInjector(BlogActivator.ORG_XTEXT_EXAMPLE_BLOG_BLOG) : null;
	}

}
